version: "3"

services: 
    app:
        build:
            dockerfile: Dockerfile
            context: .
        ports: 
            - "8080:8080"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8080"
        environment: 
            - DB_HOST=db
            - DB_USER=postgres
            - DB_NAME=app
            - DB_PASSWORD=postgres_password
        depends_on: 
            - db
    db:
        image: 'postgres:latest'
        environment:
            - POSTGRE_USER=postgres
            - POSTGRE_DB=app
            - POSTGRE_PASSWORD=postgres_password
            - POSTGRE_PORT=5432